<a href="https://colab.research.google.com/github/murli-sharma/Data-Science-ML-With-Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])
print(type(arr))
print(arr.ndim)


<class 'numpy.ndarray'>
1


In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr = np.array([1,2,3,4,5,6.6])

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
lst = [1]*10000
     

In [ ]:
print(lst)
print(len(lst))
print(type(lst))

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [ ]:
arr = np.ones(10000,dtype="uint8")

In [ ]:
print(arr)
     

[1 1 1 ... 1 1 1]


In [ ]:
%timeit sum(lst)

55.5 µs ± 928 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%timeit arr.sum()

6.88 µs ± 117 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
arr = np.ones((3,4),dtype="uint8")
print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
np.arange(1,10,2)
     

array([1, 3, 5, 7, 9])

In [ ]:
arr= np.arange(5,25,2)
print(arr)

[ 5  7  9 11 13 15 17 19 21 23]


In [ ]:
arr[2:5]
     

array([ 9, 11, 13])