<a href="https://colab.research.google.com/github/murli-sharma/Data-Science-ML-With-Python/blob/main/numpy_asignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import numpy as np

In [ ]:
import numpy as np

Create an array of 10 zeros

In [ ]:
np.zeros(10, dtype='int32')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

Create an array of 10 ones

In [ ]:
np.ones(10)

        

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Create an array of 10 fives

In [ ]:
print(np.ones(10) * 5)

print(np.full(10, 5))

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5 5 5 5 5 5 5 5 5 5]


Create an array of the integers from 10 to 50

In [ ]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Create an array of all the even integers from 10 to 50

In [ ]:
print(np.arange(10, 51, 2))


# another method
a = np.arange(10, 51)

a[ a % 2 == 0]
     

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Create a 3x4 matrix with numbers ranging from 0 to 12



In [ ]:
np.arange(12).reshape(3,4)
     

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Create a 3x3 identity matrix

In [ ]:
np.identity(3, dtype='int32')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

Use Numpy to generate a random number between 0 and 1

In [ ]:
# new method
print(np.random.random())

#
np.random.rand(1)[0] 

0.20244445925310395


0.059262342738613194

Use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
np.random.standard_normal(25).std()



np.random.randn(25).std()

0.8293112208461492

np.random.standard_normal(25).std()



np.random.randn(25).std()

In [ ]:
np.linspace(0.01, 1, 100).reshape(10, 10)
     

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

Numpy Indexing and Slicing

In [ ]:
ar = (np.arange(25)+1).reshape(5,5)
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

extract array

In [ ]:
ar[2:, 1:4]
     

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

extract array

In [ ]:
ar[2:, 3:0:-1]

array([[14, 13, 12],
       [19, 18, 17],
       [24, 23, 22]])

extract array

In [ ]:
ar[4:1:-1, 3:0:-1]

array([[24, 23, 22],
       [19, 18, 17],
       [14, 13, 12]])

Split Concatinate

In [ ]:
ar = np.arange(2,10)
ar

array([2, 3, 4, 5, 6, 7, 8, 9])

Split array to generate 3 arrays with content

In [ ]:
np.split(ar, [3,5,5])
     

[array([2, 3, 4]), array([5, 6]), array([], dtype=int64), array([7, 8, 9])]

In [ ]:
a = np.array([
              [1,2,3],
              [4,5,6]
])
b = np.array([
              [7,8,9]
])

Concatinate array to create new array with content

In [ ]:
np.vstack([a,b, b])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9]])

In [ ]:
a = np.array([
              [1,2,3],
              [4,5,6]
])
b = np.array([
              [7,8,9, 10],
              [11, 12, 13, 14]
])

Concatinate array to create new array with content

In [ ]:
np.hstack([a,b])

array([[ 1,  2,  3,  7,  8,  9, 10],
       [ 4,  5,  6, 11, 12, 13, 14]])

Broadcasting and Indexing

In [ ]:
ar = np.round(np.random.rand(10)*10)
ar

array([9., 4., 2., 5., 3., 1., 4., 2., 1., 0.])

create new array containing all numbers which are smaller than 10 in ar

In [ ]:
ar[ ar < 10 ]

array([9., 4., 2., 5., 3., 1., 4., 2., 1., 0.])

create new array containing all numbers which are in range [3, 11] in ar

In [ ]:
ar[ (ar >= 3) & (ar <= 11) ]  # & | ^ ~

array([9., 4., 5., 3., 4.])

count how many numbers are minimum in ar

In [ ]:
arr = np.round(np.random.rand(10)*10)
arr
     

array([9., 2., 4., 5., 3., 8., 8., 6., 9., 5.])

In [ ]:
arr[ arr == arr.min() ].size

1

Create an array of length 20 with first 15 numbers equal to 2 and last 5 numbers = -5

In [ ]:
a = np.ones(15)*2
b  = np.ones(5)*-5

np.concatenate([a,b])

array([ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2., -5., -5., -5., -5., -5.])

In [ ]:
mat = np.round(np.random.rand(50)*100).reshape(5,10)
mat

array([[13., 65., 19., 72., 68., 61., 22.,  2., 53., 28.],
       [30., 15., 31., 10.,  1., 24., 89., 86., 53.,  7.],
       [ 4., 52., 30., 43.,  5., 54., 93., 33.,  6., 63.],
       [43., 14., 13., 32., 29., 66., 16., 55., 17., 87.],
       [67., 69., 42., 13., 76., 38., 52., 87.,  3., 99.]])

Sum min max of all elements of matrix

In [ ]:
print(mat.min())
print(mat.max())
print(mat.sum())


1.0
99.0
2050.0


Standard deviation of mat

In [ ]:
mat.std()
     

28.094839383772957

Sum of all columns of mat

In [ ]:
mat.sum(axis=0)
     

array([157., 215., 135., 170., 179., 243., 272., 263., 132., 284.])

In [ ]:
ar = np.array([
               [1,2,3,4],
               [10,10,10,10]
])

In [ ]:
ar.sum(axis=1)

array([10, 40])

create array of dimension same as arr

In [ ]:
arr = np.arange(100).reshape(4,5,5)
     

In [ ]:
dim = arr.shape

In [ ]:
arr2 = np.arange(arr.size).reshape(arr.shape)
arr2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])